version: '3'
services:
  client:
    build:
      context: ./client
    ports:
      - "5173:5173"
    depends_on:
      - server
    environment:
      - VITE_PROXY_URL=http://server:3000

  server:
    build: .
    ports:
      - "3000:3000"