version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always

  frontend:
    build: ./client
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - backend
    restart: always
